[package]
name = "discord-macros-common"
version = "0.1.0"
edition = "2021"

[features]
derive = ["dep:darling"]

[dependencies]
darling = { workspace = true, optional = true}
serde.workspace = true
serde_json.workspace = true
ahash.workspace = true
bitflags.workspace = true